### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yezins** [jiaocoll/BeeScan-web#3]
panic: html/template: pattern matches no files: `../routers/templates/*`

goroutine 1 [running]:
html/template.Must(...)
        /usr/local/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0000856c0, {0x9a902b, 0x16})
        /Users/ameng/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:225 +0x2db
Beescan/routers.SetupRouter()
        /Users/ameng/github/BeeScan-web/routers/routers.go:48 +0xfc
main.main()
        /Users/ameng/github/BeeScan-web/cmd/BeeScan.go:18 +0x19

**Comment by jiaocoll** [comment]
已修复
