### ISSUE TITLE
如何添加节点？

### ISSUE THREAD

**Issue by yezins** [jiaocoll/BeeScan-web#4]

**Comment by jiaocoll** [comment]
1.在扫描端的配置文件中配置好节点名称，然后配置好数据库后运行节点。
2.在展示端的配置文件中配置节点名称即可，配置格式可参考初始模板。

**Comment by yezins** [comment]
两个节点配置好了，服务也没问题，但是展示端看不到节点2
![图片](https://user-images.githubusercontent.com/80327113/181715682-6ffa002e-f0ae-4fa5-98a9-51e49d36476c.png)
![图片](https://user-images.githubusercontent.com/80327113/181715885-8e1dfcc4-5366-4fe1-8d03-031d3860c0b9.png)

**Comment by jiaocoll** [comment]
请问展示端配置文件的配置图能发一下吗？是否和初始给的格式相同？

**Comment by yezins** [comment]
默认的
![图片](https://user-images.githubusercontent.com/80327113/181719041-9f0307e5-1d6d-4185-a2b5-6262e7bda36f.png)

**Comment by jiaocoll** [comment]
这是我的配置文件格式，是没有问题的。
![image](https://user-images.githubusercontent.com/62785738/181722775-0b79a773-b914-4fcf-90bc-ed90cbfea563.png)
![image](https://user-images.githubusercontent.com/62785738/181722816-7e9f1c05-bede-4562-a68a-ce2a57a7b656.png)
![image](https://user-images.githubusercontent.com/62785738/181722870-babc56cc-a5a8-4238-909b-fb24bd3cab20.png)
![image](https://user-images.githubusercontent.com/62785738/181723011-f88a732f-977a-406f-9cca-6bee0a53d589.png)
另外，yaml中用的是空格不是tab键。

**Comment by yezins** [comment]
两个节点我做的es集群，没啥问题吧

**Comment by jiaocoll** [comment]
目前未测试过es集群，展示端和扫描端之间是通过redis数据库进行交流的。

**Comment by yezins** [comment]
2台扫描端redis和es都是单独部署的，不在同一台机器

**Comment by jiaocoll** [comment]
redis和es在不在同一台机器不影响的，只需要保证你的展示端和各个扫描端节点用的数据库是一个就行。

**Comment by jiaocoll** [comment]
我觉得你可能是第二个扫描节点用的redis和展示端不是一个，所以没有产生交流，从而展示端无法获取到第二个扫描节点。

**Comment by yezins** [comment]
目前架构：展示端在机器1上，扫描端1也在机器1上，它俩共用机器1的es和redis；扫描端2在机器2上，用的机器2的es和redis

**Comment by yezins** [comment]
确实是没用同一个的原因
![图片](https://user-images.githubusercontent.com/80327113/181726312-343aeb43-ae5d-4fa0-b42c-cd5bb3f76810.png)
